In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [8]:
mat1 = np.arange(0,9).reshape(3,3)
mat2 = np.arange(1,10).reshape(3,3)
mat1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:

print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n",mat1 + mat2)
print("\nMultiplication\n------------------\n",mat1 * mat2)


print("\nDivision\n------------------\n",mat1 / mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", (mat1*3) - (2*mat2) )


print("\nAddition of a scalar (100)\n-------------------------\n", mat1 +100 )


print("\nExponentiation, matrix cubed here\n----------------------------------------\n",mat1**3) 
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n", np.sqrt(mat1))


1st Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition
------------------
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

Multiplication
------------------
 [[ 0  2  6]
 [12 20 30]
 [42 56 72]]

Division
------------------
 [[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]
 [0.85714286 0.875      0.88888889]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]

Addition of a scalar (100)
-------------------------
 [[100 101 102]
 [103 104 105]
 [106 107 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [54]:
from numpy.random import randint as ri
mat1 = np.arange(0,9).reshape(3,3)
mat2 = np.arange(1,10).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1*50)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2*50)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1*50,axis=0))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n")


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",mat2*50)
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1)*50)


mat1 =np.random.randint(1,100,100)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1*50)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1)*80)


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n")


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1)*60)



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[  0  50 100]
 [150 200 250]
 [300 350 400]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[ 50 100 150]
 [200 250 300]
 [350 400 450]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 36

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [ 3 12 21]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [450 600 750]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 


Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [[ 50 100 150]
 [200 250 300]
 [350 400 450]]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.0

Standard deviation of all numbers in 1st matrix
 -----------

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [ ]:
##Solution
*******

### 4.Sort

In [57]:
A = np.random.randint(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [17 58 59 36 56 29 20 31 47 15]

Here is the sorted vector
 -------------------------------------------------- 
 [15 17 20 29 31 36 47 56 58 59]


In [66]:
M = np.random.randint(0,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M*50)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M*50,axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M*50,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[3750  350 3350 4250 4650]
 [2850 2950 1850 1700 2200]
 [1700  500 4900 4800 1250]
 [4650 1500 4450  850 1400]
 [3400 4900 2300  450 2950]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 350 3350 3750 4250 4650]
 [1700 1850 2200 2850 2950]
 [ 500 1250 1700 4800 4900]
 [ 850 1400 1500 4450 4650]
 [ 450 2300 2950 3400 4900]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[1700  350 1850  450 1250]
 [2850  500 2300  850 1400]
 [3400 1500 3350 1700 2200]
 [3750 2950 4450 4250 2950]
 [4650 4900 4900 4800 4650]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [71]:
# Fill the following ***** with appropriate solution.
a=np.random.randint(1,100,10)
b=np.random.randint(1,100,10)
c=np.random.randint(1,100,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:",np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:",a.argmax())
print("Max of b location:",b.argmax())
print("Max of c location:",c.argmax())





a: [31 79 34 63 82 96 51 40  1 95]
b: [67  4 98 61 56 72 78 57  3 26]
c: [66  9 38 86 37 93 44  1 65 24]
Max of a: 96
Max of b: 98
Max of a location: 5
Max of b location: 2
Max of c location: 5


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [20]:
import numpy as np
mat1 = np.random.randint(0,9,9).reshape(3,3)
mat2 =  np.random.randint(1,100,9).reshape(3,3)


print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n",np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n",mat1**mat2*50)


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n",np.log(mat1)*50)


print("\nModulo reminder using np\n",'-'*50,"\n")



1st Matrix of random single-digit numbers
----------------------------------------
 [[1 2 5]
 [2 1 4]
 [1 8 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[78 58 24]
 [81 37 72]
 [29  9 12]]

Sq-root of 1st matrix using np
------------------
 [[1.         1.41421356 2.23606798]
 [1.41421356 1.         2.        ]
 [1.         2.82842712 2.82842712]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[         50           0  1678141810]
 [          0          50           0]
 [         50 -1879048192           0]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[  0.          34.65735903  80.47189562]
 [ 34.65735903   0.          69.31471806]
 [  0.         103.97207708 103.97207708]]

Modulo reminder using np
 -------------------------------------------------- 



### 7.Generating matrices from distributions

In [24]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(6).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print("")

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print("") #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,6,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.58965874 0.72562356 0.75842689]
 [0.78573885 0.83689266 0.61007892]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal

Random integer vector: [91  6 16 99 35 50 55 93 11 37]

Random integer matrix


20 samples drawn from a dice throw: [2 2 4 4 3 1 2 1 1 2 4 3 1 5 4 3 4 1 4 5]


### 8.Find the nearest value from a given number in an array using NumPy.

In [34]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

m1=np.random.randint(1,12,5)
m2=10
print(m1)
print(m2-m1)
print(m1[(m2-m1).argmin()])

[7 3 4 2 8]
[3 7 6 8 2]
8


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [65]:
m1=np.arange(0,3)*0
m1.reshape(1,3)
m2=np.arange(0,3)
m2.reshape(1,3)
m3=np.arange(0,3)*2
m3.reshape(1,3)
m4=np.append(m1,m2,axis=0)
np.append(m4,m3,axis=0).reshape(3,3)


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])